const fs = require("fs");

// Verilen metin//
const originalText = `A


"Abbas عبّاس ( Ebced Değeri: 135 )"
"Abdülaziz عبدالعزيز ( Ebced Değeri: 201 )"
"Abdülcabbar عبدالجبّار ( Ebced Değeri: 201 )"
"Abdulfettah عبدالفتّاح ( Ebced Değeri: 315 )"
"Abdulgaffar عبدالغفّار ( Ebced Değeri: 1468 )"
"Abdulhamit عبدالحميد ( Ebced Değeri: 565 )"
"Abdülhakim عبدالحكيم(  Ebced Değeri: 265 )"
"Abdülkerim عبدالكريم ( Ebced Değeri: 377 )"
"Abdulmecit عبدالمجيد ( Ebced Değeri: 560 )"
"Abdullatif عبداللطيف ( Ebced Değeri: 628 )"
"Abdusselam عبدالسلام ( Ebced Değeri: 238 )"
"Abdussamet عبدالصمد ( Ebced Değeri: 241 )"
"Abdulvahap عبدالوهّاب ( Ebced Değeri: 121 )"
"Abdi عبدى ( Ebced Değeri: 86 )"
"Abdulhakim عبدالحكيم ( Ebced Değeri: 185 )"
"Abdulkadîr عبدالقدير ( Ebced Değeri: 421 )"
"Abdullah عبدالله ( Ebced Değeri: 143 )"
"Abdurrahim عبدالرّحمن ( Ebced Değeri: 565 )"
"Abdurrahman عبدالرّحمن ( Ebced Değeri: 405 )"
"Abdülbâki عبدالباقى ( Ebced Değeri: 220 )"
"Abdüssamed عبدالصّمد ( Ebced Değeri: 331 )"
"Acar آجار ( Ebced Değeri: 205 )"
"Adahan آداخان ( Ebced Değeri: 657 )"
"Adak آداق ( Ebced Değeri: 106 )"
"Adalet عدالت ( Ebced Değeri: 505 )"
"Adem آدم ( Ebced Değeri: 45 )"
"Adviye عدويه ( Ebced Değeri: 95 )"
"Adıgüzel آديكوزل ( Ebced Değeri: 78 )"
"Adil عادل ( Ebced Değeri: 105 )"
"Adile عادله ( Ebced Değeri: 110 )"
"Adnan عدنان ( Ebced Değeri: 175 )"
"Afet آفت ( Ebced Değeri: 481 )"
"Afife عفيفه ( Ebced Değeri: 245 )"
"Afitap آفتاب ( Ebced Değeri: 484 )"
"Afşar آفشار ( Ebced Değeri: 582 )"
"Alaaddin علاءالدين ( Ebced Değeri: 197 )"
"Aleyna علينا ( Ebced Değeri: 161 )"
"Azra  عزراء ( Ebced Değeri: 971 )"
"Azize  عزيزة ( Ebced Değeri: 245 )"
"Aziz  عزيز ( Ebced Değeri: 94 )"
"Atiye  عطيّة ( Ebced Değeri: 94 )"
"Atıf  عاطف ( Ebced Değeri: 160 )"
"Asım  عاصم ( Ebced Değeri: 201 )"
"Ahsen أحسن ( Ebced Değeri: 119 )"
"Ahu آهو ( Ebced Değeri: 12 )"
"Ahmet احمد ( Ebced Değeri: 53 )"
"Ayşe عاءشه ( Ebced Değeri: 377 )"
"Ayşegül عاءشه كل ( Ebced Değeri: 426 )"
"Ayşenur عاءشه نور ( Ebced Değeri: 632 )"
"Ajda اژدا ( Ebced Değeri: 13 )"
"Akif عاكف ( Ebced Değeri: 171 )"
"Ali على ( Ebced Değeri: 110 )"
"Alime عالمه ( Ebced Değeri: 146 )"
"Aliye عليه ( Ebced Değeri: 115 )"
"Alpcan آلپ جان ( Ebced Değeri: 87 )"
"Alper آلپر ( Ebced Değeri: 233 )"
"Altan آلتان ( Ebced Değeri: 482 )"
"Arif عارف ( Ebced Değeri: 341 )"
"Arife عارفه ( Ebced Değeri: 346 )"
"Arzu آرزو ( Ebced Değeri: 214 )"
"Asiye آسيه ( Ebced Değeri: 76 )"
"Aslı اصلي ( Ebced Değeri: 131 )"
"Aslıhan اصليخان ( Ebced Değeri: 782 )"
"Asuman آسمان ( Ebced Değeri: 152 )"
"Atatürk آتاتورك ( Ebced Değeri: 1028 )"
"Atilla آتيلاّ ( Ebced Değeri: 272 )"
"Aydın آيدين ( Ebced Değeri: 75 )"
"Ayfer آيفر ( Ebced Değeri: 291 )"
"Aykutalp آيقود آلپ ( Ebced Değeri: 154 )"
"Ayla آيلا ( Ebced Değeri: 42 )"
"Aynur آينور ( Ebced Değeri: 267 )"
"Aysel آيسل ( Ebced Değeri: 101 )"
"Aysun آيسون ( Ebced Değeri: 127 )"
"Ayten آيتن ( Ebced Değeri: 461 )"
"Aytunç آيتونچ ( Ebced Değeri: 469 )"
"Aytül آيتول ( Ebced Değeri: 447 )"

"Baha بهاء  ( Ebced Değeri: 8 )"
"Bahar بهار ( Ebced Değeri: 208 )"
"Bahattin بهاءالدين ( Ebced Değeri: 104 )"
"Bahaddîn بهاالدّين ( Ebced Değeri: 107 )"
"Bahadır بهادر ( Ebced Değeri: 212 )"
"Bânû بانو ( Ebced Değeri: 59 )"
"Bedia بديعة ( Ebced Değeri: 91 )"
"Bedir بدر ( Ebced Değeri: 206 )"
"Bedriye بدريه ( Ebced Değeri: 221 )"
"Begüm بكوم ( Ebced Değeri: 68 )"
"Bekir بكر ( Ebced Değeri: 222 )"
"Belgin بلكين ( Ebced Değeri: 112 )"
"Belkıs بلقيس ( Ebced Değeri: 202 )"
"Belgüzar برگزار ( Ebced Değeri: 430 )"
"Berk  برق ( Ebced Değeri: 302 )"
"Berkant برقانت ( Ebced Değeri: 753 )"
"Berkay بركاى ( Ebced Değeri: 233 )"
"Bernâ برنا ( Ebced Değeri: 253 )"
"Besime بسيمه ( Ebced Değeri: 117 )"
"Bertan برتان ( Ebced Değeri: 653 )"
"Berrak برّاق ( Ebced Değeri: 503 )"
"Betül بتول ( Ebced Değeri: 438 )"
"Beyhan بيخان ( Ebced Değeri: 663 )"
"Beyza بيضا ( Ebced Değeri: 813 )"
"Bilal بلال ( Ebced Değeri: 63 )"
"Birgül بيركل ( Ebced Değeri: 262 )"
"Birol بيرول ( Ebced Değeri: 248 )"
"Birsel بيرسل ( Ebced Değeri: 302 )"
"Bora بورا ( Ebced Değeri: 438 )"
"Buket بوكت ( Ebced Değeri: 428 )"
"Burak براق ( Ebced Değeri: 303 )"
"Burcu برجو ( Ebced Değeri: 211 )"
"Burhan برهان ( Ebced Değeri: 258 )"
"Büşra بشرى ( Ebced Değeri: 512 )"

"Câhid جاهد ( Ebced Değeri: 13 )"
"Cahide جاهدة ( Ebced Değeri: 18 )"
"Canan جانان ( Ebced Değeri: 115 )"
"Candan جاندن ( Ebced Değeri: 108 )"
"Cansu جانصو ( Ebced Değeri: 150 )"
"Cemal جمال ( Ebced Değeri: 74 )"
"Cemalettin جمال الدين ( Ebced Değeri: 173 )"
"Cemil جميل ( Ebced Değeri: 83 )"
"Cemile جميله ( Ebced Değeri: 88 )"
"Cennet جنّة ( Ebced Değeri: 503 )"
"Cengiz جنكيز ( Ebced Değeri: 90 )"
"Cenker جنكر ( Ebced Değeri: 273 )"
"Ceren جرن ( Ebced Değeri: 253 )"
"Cevahir جواهر ( Ebced Değeri: 215 ) "
"Cevdet جودت ( Ebced Değeri: 413 ) "
"Cihan جهان ( Ebced Değeri: 59 )"
"Cihangir جهانگير ( Ebced Değeri: 289 )"
"Cihat جهاد ( Ebced Değeri: 13 )"
"Cihangir جهانگير ( Ebced Değeri: 289 )"
"Coşkun جوشقون ( Ebced Değeri: 465 )"
"Cüneyd (Cüneyt) جنيد ( Ebced Değeri: 67 )"


"Çağla چاغلا ( Ebced Değeri: 1035 )"
"Çiçek چيچك ( Ebced Değeri: 36 )  "
"Çiğdem چيكدم ( Ebced Değeri: 77 )"

"Damla داملا ( Ebced Değeri: 76 )"
"Dâvud (Davut) داود ( Ebced Değeri: 15 )"
"Deniz دگيز ( Ebced Değeri: 42 )"
"Derya دريا ( Ebced Değeri: 215 )"
"Devlet دولت ( Ebced Değeri: 440 )"
"Dilara دلآرا ( Ebced Değeri: 236 )"
"Dilber دلبر ( Ebced Değeri: 236 )"
"Dilek ديلك ( Ebced Değeri: 64 )"
"Doğan دوغان ( Ebced Değeri: 1061 )"
"Döne دونه ( Ebced Değeri: 65 )"
"Durdu دوردو ( Ebced Değeri: 220 )"
"Dursûne دورسونه ( Ebced Değeri: 330 )"
"Dürdâne دوردانه ( Ebced Değeri: 270 )"

"Ebrû ابرو ( Ebced Değeri: 209 )"
"Ebu bekir  أبو بكر ( Ebced Değeri: 101 )"
"Ece اجه ( Ebced Değeri: 9 )"
"Ecehan (Ece-Hân) اجه خان ( Ebced Değeri: 660 )"
"Ecmel اجمل ( Ebced Değeri: 74 )"
"Edâ أدا ( Ebced Değeri: 6 )"
"Edibe   أديبة ( Ebced Değeri: 22 )"
"Edip  أديب ( Ebced Değeri: 17 )"
"Efe أفه ( Ebced Değeri: 86 )"
"Ekrem اكرم ( Ebced Değeri: 261 )"
"Elif الف ( Ebced Değeri: 111 )"
"Elmas الماس ( Ebced Değeri: 132 )"
"Elvân الف ( Ebced Değeri: 88 )"
"Emel أمل ( Ebced Değeri: 71 )"
"Emin  أمين ( Ebced Değeri: 101 )"
"Emine امنه ( Ebced Değeri: 96 )"
"Emir  أمير ( Ebced Değeri: 251 )"
"Emrâl أمرال ( Ebced Değeri: 272 )"
"Emre أمره ( Ebced Değeri: 246 )"
"Ender اندر ( Ebced Değeri: 255 )"
"Enes أنس ( Ebced Değeri: 111 )"
"Enîse أنيسة ( Ebced Değeri: 122 )"
"Enis أنيس ( Ebced Değeri: 121 )"
"Eray أراى ( Ebced Değeri: 212 )"
"Erhan أرخان ( Ebced Değeri: 852 )"
"Erkan أرقان ( Ebced Değeri: 352 )"
"Ermân أرمان ( Ebced Değeri: 292 )"
"Erol أرول ( Ebced Değeri: 237 )"
"Ertuğrul أرتوغرول ( Ebced Değeri: 1843 )"
"Esengül اسنكل ( Ebced Değeri: 161 )"
"Esrâ أسرا ( Ebced Değeri: 262 )"
"Esma أسماء ( Ebced Değeri: 102 )"
"Evren اورن ( Ebced Değeri: 257 )"

"Fadime فاطمه ( Ebced Değeri: 135 )"
"Fatma فاطمه ( Ebced Değeri: 135 )"
"Faruk فاروق ( Ebced Değeri: 387 )"
"Fatih فاتح ( Ebced Değeri: 489 )"
"Fatoş فاطوش ( Ebced Değeri: 396 )"
"Fazıl فاضل ( Ebced Değeri: 911 )"
"Fazilet فضيلت ( Ebced Değeri: 1320 )"
"Fehime فهيمه ( Ebced Değeri: 140 )"
"Ferâmuz فرامز ( Ebced Değeri: 328 )"
"Ferhat فرهاد ( Ebced Değeri: 290 )"
"Ferhan فرحان ( Ebced Değeri: 290 )"
"Feride فريده ( Ebced Değeri: 339 )"
"Feridûn فريدون ( Ebced Değeri: 350 )"
"Feriha فرحه ( Ebced Değeri: 293 )"
"Ferişte فرشته ( Ebced Değeri: 985 )"
"Ferit فريد ( Ebced Değeri: 294 )"
"Fethiye فتحيه ( Ebced Değeri: 503 )"
"Fethullah فتح الله ( Ebced Değeri: 554 )"
"Feyzâ فيضا ( Ebced Değeri: 891 )"
"Fırat فرات ( Ebced Değeri: 671 )"
"Figen فيكن ( Ebced Değeri: 160 )"
"Fikriye فكريه ( Ebced Değeri: 315 )"
"Filiz فيليز ( Ebced Değeri: 137 )"
"Firdevs فردوس ( Ebced Değeri: 350 )"
"Fuat فؤاد ( Ebced Değeri: 91 )"

"Galip غالب ( Ebced Değeri: 1033 )"
"Gani غنيّ ( Ebced Değeri: 1060 )"
"Gamze غمزه ( Ebced Değeri: 1052 )"
"Gazâlî غزالى ( Ebced Değeri: 1741 )"
"Gâzî غازى ( Ebced Değeri: 1018 )"
"Gizem گيزم ( Ebced Değeri: 77 )"
"Gonca غنجه ( Ebced Değeri: 1058 )"
"Gِökçe كوكچه ( Ebced Değeri: 54 )"
"Gökçe كوكچه ( Ebced Değeri: 54 )"
"Gökhan كوكحان ( Ebced Değeri: 697 )"
"Gökmen كوكمن ( Ebced Değeri: 136 )"
"Göksel كوكسل ( Ebced Değeri: 136 )"
"Gökşen كوكشن ( Ebced Değeri: 396 )"
"Göktay كوكطى ( Ebced Değeri: 65 )"
"Gönül كوڭل ( Ebced Değeri: 76 )"
"Görkem كوركم ( Ebced Değeri: 286 )"
"Gözde كوزده ( Ebced Değeri: 42 )"
"Gül كل ( Ebced Değeri: 50 )"
"Gülay كُلاى ( Ebced Değeri: 61 )"
"Gülcan كُلجان ( Ebced Değeri: 104 )"
"Gülden كلدن ( Ebced Değeri: 104 )"
"Güler كولر ( Ebced Değeri: 256 )"
"Gülhan كولخان ( Ebced Değeri: 707 )"
"Gülistan كلستان ( Ebced Değeri: 561 )"
"Gülizar كُلعذار ( Ebced Değeri: 328 )"
"Güllü كُللو ( Ebced Değeri: 86 )"
"Gülnaz كلناز ( Ebced Değeri: 108 )"
"Gülsüm كولسوم ( Ebced Değeri: 162 )"
"Gülsen كولسن ( Ebced Değeri: 166 )"
"Gülser كُلسر ( Ebced Değeri: 310 )"
"Gülseren كُلسرن ( Ebced Değeri: 360 )"
"Gülşah كلشاه ( Ebced Değeri: 359 )"
"Gülşen گلشن ( Ebced Değeri: 400 )"
"Gülten كُلتن ( Ebced Değeri: 500 )"
"Günay كناى ( Ebced Değeri: 81 )"
"Günseli كونسلى ( Ebced Değeri: 176 )"
"Gürbüz كربز ( Ebced Değeri: 229 )"
"Gürcân كورجان ( Ebced Değeri: 280 )"

"Habib حبيب ( Ebced Değeri: 22 )"
"Habibe حبيبه ( Ebced Değeri: 27 )"
"Hacer حجر ( Ebced Değeri: 211 )"
"Hadi هادي ( Ebced Değeri: 20 )"
"Hafsa حَفْصَة ( Ebced Değeri: 183 )"
"Hakan خاقان ( Ebced Değeri: 752 )"
"Halide خالده ( Ebced Değeri: 640 )"
"Halil خليل ( Ebced Değeri: 670 )"
"Halim حليم ( Ebced Değeri: 88 )"
"Halime حليمه ( Ebced Değeri: 93 )"
"Halis خالص ( Ebced Değeri: 721 )"
"Halise خالصة ( Ebced Değeri: 21 )"
"Halit خالد ( Ebced Değeri: 635 )"
"Haluk خلوق ( Ebced Değeri: 736 )"
"Hamdiye حمديه ( Ebced Değeri: 67 )"
"Hamide حميده ( Ebced Değeri: 67 )"
"Hamit حميد ( Ebced Değeri: 53 )"
"Hamza حمزة ( Ebced Değeri: 60 )"
"Handan خندان ( Ebced Değeri: 705 )"
"Hanım خانم ( Ebced Değeri: 691 )"
"Hanife حنيفه ( Ebced Değeri: 153 )"
"Hanifi حنيفى ( Ebced Değeri: 158 )"
"Hansa خَنْسَاء ( Ebced Değeri: 711 )"
"Harun هارون ( Ebced Değeri: 262 )"
"Hasan حسن ( Ebced Değeri: 118 )"
"Hasîbe حسيبه ( Ebced Değeri: 85 )"
"Hasbiye حسبيه ( Ebced Değeri: 85 )"
"Haşim هاشم ( Ebced Değeri: 346 )"
"Hatem خاتم ( Ebced Değeri: 1041 )"
"Hatîce خديجه ( Ebced Değeri: 622 )"
"Havva حوّاء ( Ebced Değeri: 21 )"
"Havvâ حوّا ( Ebced Değeri: 21 )"
"Havvâgül حوّا كل ( Ebced Değeri: 71 )"
"Hayriye خيريه ( Ebced Değeri: 825 )"
"Hediye هديّة ( Ebced Değeri: 24 )"
"Hikmet حكمة ( Ebced Değeri: 468 )"
"Hilal هلال ( Ebced Değeri: 66 )"
"Hûrî حورى ( Ebced Değeri: 224 )"
"Hûriye حوريه ( Ebced Değeri: 229 )"
"Hürüşan خروشان ( Ebced Değeri: 1157 )"
"Hülya خوليا ( Ebced Değeri: 647 )"
"Hümeyra حميره ( Ebced Değeri: 263 )"
"Hüsamettin حسامالدين ( Ebced Değeri: 204 )"  
"Hüseyin حسين ( Ebced Değeri: 128 )"
"Hüsne حسنه ( Ebced Değeri: 123 )"

"İbrâhim ابراهيم ( Ebced Değeri: 259 )"
"İfakat افاقت ( Ebced Değeri: 582 )"
"İhsân احسان ( Ebced Değeri: 120 )"
"İklime اقليمه ( Ebced Değeri: 186 )"
"İlhan ايلخان ( Ebced Değeri: 692 )"
"İlknur ايلكنور ( Ebced Değeri: 217 )"
"İlyâs الياس ( Ebced Değeri: 102 )"
"İmren إمرن ( Ebced Değeri: 291 )"
"İnci اينجى ( Ebced Değeri: 74 )"
"İrfan عرفان ( Ebced Değeri: 401 )"
"İsâ عيسى ( Ebced Değeri: 150 )"
"İsmâil اسماعيل ( Ebced Değeri: 212 )"
"İsmet عصمت ( Ebced Değeri: 600 )"
"İzzet  عزّة ( Ebced Değeri: 484 )"

"Kadîr قدير ( Ebced Değeri: 314 )"
"Kadri قدري ( Ebced Değeri: 314 )"
"Kadriye قدريه ( Ebced Değeri: 319 )"
"Kâniye كانيه ( Ebced Değeri: 86 )"
"Kamer قمر ( Ebced Değeri: 340 )"
"Kamil كامل ( Ebced Değeri: 91 )"
"Kemâl كمال ( Ebced Değeri: 91 )"
"Kerem كرم ( Ebced Değeri: 260 )"
"Kerim كريم ( Ebced Değeri: 270 )"
"Kevser كوثر ( Ebced Değeri: 726 )"
"Kezban كذبان ( Ebced Değeri: 773 )"
"Kısmet قسمت ( Ebced Değeri: 600 )"
"Kıymet قيمة ( Ebced Değeri: 155 )"
"Kibar كبار ( Ebced Değeri: 223 )"
"Kubilay قوبيلاى ( Ebced Değeri: 159 )"
"Kudret قدرت ( Ebced Değeri: 704 )"
"Kübra كبرا ( Ebced Değeri: 223 )"
"Kürşat كورشات ( Ebced Değeri: 927 )"

"Lâle لاله ( Ebced Değeri: 66 )"
"Leylâ ليلا ( Ebced Değeri: 71 )"
"Lütfi لطفي ( Ebced Değeri: 129 )"

"Macit ماجد ( Ebced Değeri: 48 )"
"Mahbub محبوب ( Ebced Değeri: 58 )"
"Mahir ماهر ( Ebced Değeri: 246 )"
"Mahire ماهره ( Ebced Değeri: 251 )"
"Mahmut محمود ( Ebced Değeri: 98 )"
"Maide ماءده ( Ebced Değeri: 51 )"
"Mahzun  محزون ( Ebced Değeri: 111 )"
"Makbule مقبوله ( Ebced Değeri: 183 )"
"Mecit مجيد ( Ebced Değeri: 57 )"
"Mediha ممديحه ( Ebced Değeri: 67 )"
"Mehmet محمد ( Ebced Değeri: 92 )"
"Mehtap مهتاب ( Ebced Değeri: 448 )"
"Melahat ملاحت ( Ebced Değeri: 479 )"
"Melek ملك ( Ebced Değeri: 90 )"
"Meliha مليحه ( Ebced Değeri: 93 )"
"Melike ملكه ( Ebced Değeri: 95 )"
"Melis مَليس ( Ebced Değeri: 140 )"
"Meltem ملتم ( Ebced Değeri: 510 )"
"Meral مرال ( Ebced Değeri: 271 )"
"Mersiye مرثيه ( Ebced Değeri: 755 )"
"Merve مروه ( Ebced Değeri: 251 )"
"Meryem مريم ( Ebced Değeri: 290 )"
"Mesut مسعود ( Ebced Değeri: 180 )"
"Mete مهته ( Ebced Değeri: 450 )"
"Metin متين ( Ebced Değeri: 500 )"
"Mihriban مهربان ( Ebced Değeri: 298 )"
"Mine مينه ( Ebced Değeri: 105 )"
"Miyase مياسه ( Ebced Değeri: 116 )"
"Muammer معمّر ( Ebced Değeri: 390 )"
"Muazzez معزّز ( Ebced Değeri: 131 )"
"Muhammet محمّد ( Ebced Değeri: 132 )"
"Murat مراد ( Ebced Değeri: 245 )"
"Musa موسى ( Ebced Değeri: 116 )"
"Mustafa مصطفى ( Ebced Değeri: 229 )"
"Mutlu موتلو ( Ebced Değeri: 482 )"
"Mübeccel مبجّل ( Ebced Değeri: 78 )"
"Mücahit مجاهد ( Ebced Değeri: 53 ) "
"Mücevher مجوهر ( Ebced Değeri: 254 )"
"Münevver منوّر ( Ebced Değeri: 302 )"
"Münire منيره ( Ebced Değeri: 305 )"
"Mürüvvet مروّت ( Ebced Değeri: 652 )"
"Müsade مصاده ( Ebced Değeri: 140 )"
"Müzeyyen مزيّن ( Ebced Değeri: 117)"

"Naciye ناجيه ( Ebced Değeri: 69 )"
"Nadide ناديده ( Ebced Değeri: 74 )"
"Nadire نادرة ( Ebced Değeri: 260 )"
"Naile نائله ( Ebced Değeri: 87 )"
"Nafi نافع ( Ebced Değeri: 201 )"
"Naime نائمه ( Ebced Değeri: 97 )"
"Nalan نالان ( Ebced Değeri: 132 )"
"Narin نارين ( Ebced Değeri: 311 )"
"Naz ناز ( Ebced Değeri: 58 )"
"Nazif نظيف ( Ebced Değeri: 1040 )"
"Nazife نظيفه ( Ebced Değeri: 1045 )"
"Nazire نظيره ( Ebced Değeri: 1165 )"
"Nazlı نازلى ( Ebced Değeri: 351 )"
"Nazmiye نظميه ( Ebced Değeri: 1005 )"
"Necdet نجدت ( Ebced Değeri: 457 )"
"Necla نجلا ( Ebced Değeri: 84 )"
"Necmettin نجم الدين ( Ebced Değeri: 188 )"
"Necmiye نجميه ( Ebced Değeri: 108 )"
"Nejat نجاة ( Ebced Değeri: 62 ) "
"Nergis نركس ( Ebced Değeri: 330 )"
"Neriman نريمان ( Ebced Değeri: 1005 )"
"Nermin نرمين ( Ebced Değeri: 350 )"
"Nesibe نسيبه ( Ebced Değeri: 127 )"
"Nesime نسيمه ( Ebced Değeri: 165 )"
"Neslihan نسليخان ( Ebced Değeri: 801 )"
"Nesrin نسرين ( Ebced Değeri: 370 )"
"Nevin نوين ( Ebced Değeri: 116 )"
"Nevriye نوريه ( Ebced Değeri: 271 )"
"Nevzat نوزاد ( Ebced Değeri: 70 )"
"Nezihe نزيهه ( Ebced Değeri: 77 )"
"Nigar نكار ( Ebced Değeri: 271 )"
"Nihal نهال ( Ebced Değeri: 86 )"
"Nihat نهاد ( Ebced Değeri: 60 )"
"Nil نيل ( Ebced Değeri: 90 )"
"Nilay نيلاي ( Ebced Değeri: 101 )"
"Nilüfer نيلوفر ( Ebced Değeri: 376 )"
"Nilva نيلوا ( Ebced Değeri: 97 )"
"Nimet نعمت ( Ebced Değeri: 460 )"
"Numan نعمان ( Ebced Değeri: 211 )"
"Nur نور ( Ebced Değeri: 256 )"
"Nurşen نورشن ( Ebced Değeri: 606 )"
"Nuran نوران ( Ebced Değeri: 307 )"
"Nuray نوراى ( Ebced Değeri: 267 )"
"Nurcan نورجان ( Ebced Değeri: 310 )"
"Nurettin  نور الدين ( Ebced Değeri: 355 )"
"Nuri نورى ( Ebced Değeri: 266 )"
"Nuriye نوريه ( Ebced Değeri: 271 )"
"Nursel نورسل ( Ebced Değeri: 346 )"
"Nurseli نورسلى ( Ebced Değeri: 356 )"
"Nurten نورتن ( Ebced Değeri: 706 )"
"Nurullah نورالله ( Ebced Değeri: 322 )"

"Oğuz اوغوز ( Ebced Değeri: 1020 )"
"Oğuzhan اوغوزخان ( Ebced Değeri: 1671 )"
"Okan اوقان ( Ebced Değeri: 158 )"
"Olcay اولجاى ( Ebced Değeri: 51 )"
"Onur اونور ( Ebced Değeri: 263 )"
"Oruç اوروچ ( Ebced Değeri: 216 )"
"Orhan اورخان ( Ebced Değeri: 858 )"
"Osman عثمان ( Ebced Değeri: 661 )"
"Oya اويا ( Ebced Değeri: 18 )"
"Ozan اوزان ( Ebced Değeri: 65 )"

"Ömer عمر ( Ebced Değeri: 310 )"
"Önder اوگدر ( Ebced Değeri: 231 )"
"Özay اوزاى ( Ebced Değeri: 25 )"
"Özcan اوزجان ( Ebced Değeri: 68 )"
"Özge اوزكه ( Ebced Değeri: 39 )"
"Özgül ازكل ( Ebced Değeri: 58 )"
"Özgünaz اوزكوناز ( Ebced Değeri: 99 )"
"Özgür اوزكور ( Ebced Değeri: 240 )"
"Özlem اوزلم ( Ebced Değeri: 84 )"
"Öznur اوزنور ( Ebced Değeri: 270 )"

"Pakize باكيزه ( Ebced Değeri: 45 )"
"Pelin بلين ( Ebced Değeri: 92 )"
"Peral برال ( Ebced Değeri: 233 )"
"Pembe بمبه ( Ebced Değeri: 49 )"
"Perihan بريخان ( Ebced Değeri: 863 )"
"Pınar بيگار ( Ebced Değeri: 233 )"

"Rabia رابعه ( Ebced Değeri: 282 )"
"Radiye راضيه ( Ebced Değeri: 1016 )"
"Ragıp راغب ( Ebced Değeri: 1203 )"
"Rahmet رحمة ( Ebced Değeri: 253)"
"Rahmi رحمى ( Ebced Değeri: 25 ) "
"Raif رائف ( Ebced Değeri: 282 ) "
"Ramazan رمضان ( Ebced Değeri: 1091 )"
"Raşit راشد ( Ebced Değeri: 505 )"
"Râziye رازيه ( Ebced Değeri: 223 )"
"Reşat رشاد ( Ebced Değeri: 505 )"
"Reşit رشيد ( Ebced Değeri: 514 )"
"Recep رجب ( Ebced Değeri: 205 )"
"Refik رفيق ( Ebced Değeri: 390 )"
"Refika رفيقه ( Ebced Değeri: 395 )"
"Remzi رمزى ( Ebced Değeri: 257 )"
"Remziye رمزيه ( Ebced Değeri: 262 )"
"Resul رسول ( Ebced Değeri: 296 )"
"Reyhan ريخان ( Ebced Değeri: 861 )"
"Reyyan ريّان ( Ebced Değeri: 271 )"
"Rıdvân رضوان ( Ebced Değeri: 1057 )"
"Ruhiye روحيه ( Ebced Değeri: 229 )"
"Rukiye رقيه ( Ebced Değeri: 315 )"
"Rümeysa رُميسا ( Ebced Değeri: 311 )"
"Rüveyda رويده ( Ebced Değeri: 225 )"
"Rıza  رضاء ( Ebced Değeri: 1001 )"
"Rıfkı رفقی ( Ebced Değeri: 390 )"

"Saadet سعادت ( Ebced Değeri: 535 )"
"Sabahat صباحت ( Ebced Değeri: 501 )"
"Sabiha صبيحه ( Ebced Değeri: 115 )"
"Sabire صبيره ( Ebced Değeri: 307 )"
"Sabriye صبريه ( Ebced Değeri: 307 )"
"Sadık صادق ( Ebced Değeri: 195 )"
"Saffet صفوت ( Ebced Değeri: 576 )"
"Safiye صفيه ( Ebced Değeri: 185 )"
"Saide سعيده ( Ebced Değeri: 149 )"
"Saime صائمه ( Ebced Değeri: 137 )"
"Sait سعيد ( Ebced Değeri: 144 )"
"Sakine ساكنه ( Ebced Değeri: 136 )"
"Salih صالح ( Ebced Değeri: 129 )"
"Saliha صالحه ( Ebced Değeri: 134 )"
"Salim سالم ( Ebced Değeri: 131 )"
"Salime سالمه ( Ebced Değeri: 136 )"
"Samet صمد ( Ebced Değeri: 134 )"
"Sami سامى ( Ebced Değeri: 111 )"
"Sanem صنم ( Ebced Değeri: 180 )"
"Saniye ثانيه ( Ebced Değeri: 566 )"
"Seçil سچيل ( Ebced Değeri: 103 )"
"Seda صدا ( Ebced Değeri: 95 )"
"Sedat سداد ( Ebced Değeri: 69 )"
"Sefa سفا ( Ebced Değeri: 141 )"
"Seher سحر ( Ebced Değeri: 268 )"
"Selahattin صلاحالدّين ( Ebced Değeri: 228 )"
"Selçuk سلچوق ( Ebced Değeri: 199 )"
"Selda سلدا ( Ebced Değeri: 95 )"
"Seleme سلمة ( Ebced Değeri: 145 )"
"Selim سليم ( Ebced Değeri: 140 )"
"Selîm سليم ( Ebced Değeri: 140 )"
"Selime سليمة ( Ebced Değeri: 145 )"
"Selma سلما ( Ebced Değeri: 131 )"
"Selman سلمان ( Ebced Değeri: 181 )"
"Selvi سلوى ( Ebced Değeri: 106 )"
"Sema سماء ( Ebced Değeri: 101 )"
"Semahat سماحت ( Ebced Değeri: 509 )"
"Semih سميح ( Ebced Değeri: 118 )"
"Semiha سميحه ( Ebced Değeri: 123 )"
"Semra سمرا ( Ebced Değeri: 301 )"
"Sena ثناء  ( Ebced Değeri: 551 )"
"Serap سراپ / سراب ( Ebced Değeri: 263 )"
"Serdar سردار ( Ebced Değeri: 465 )"
"Serkan سرقان ( Ebced Değeri: 411 )"
"Sermet سرمد ( Ebced Değeri: 304 )"
"Sermin سرمين ( Ebced Değeri: 360 )"
"Serpil سرپل ( Ebced Değeri: 292 )"
"Servet ثروت ( Ebced Değeri: 1106 )"
"Sevdâ سودا, ( Ebced Değeri: 71)"
"Sevgi سَوكى ( Ebced Değeri: 96 )"
"Sevim سَويم ( Ebced Değeri: 116 )"
"Seyfeddin سيفالدين ( Ebced Değeri: 245 )"
"Seyfettin سيفالدين ( Ebced Değeri: 245 )"
"Seyfullah سيفالله ( Ebced Değeri: 216 )"
"Sıddık صدّيق ( Ebced Değeri: 208 )"
"Sibel سيبل ( Ebced Değeri: 102 )"
"Sinan سنان ( Ebced Değeri: 161 )"
"Suat  سعاد ( Ebced Değeri: 135 )"
"Sultan سلطان ( Ebced Değeri: 150 )"
"Suna صونا ( Ebced Değeri: 147 )"
"Suzan سوزن ( Ebced Değeri: 123 )"
"Süheyla سهيلا ( Ebced Değeri: 106 )"
"Süleyman سليمان (  Ebced Değeri: 191 )"
"Sünbül سنبل ( Ebced Değeri: 142)"

"Şaban شعبان ( Ebced Değeri: 423 )"
"Şâdiye شاديه ( Ebced Değeri: 320 )"
"Şâfak شفاق ( Ebced Değeri: 481 )"
"Şâfiye شافيه ( Ebced Değeri: 396 )"
"Şâheserشاه أثر ( Ebced Değeri: 1007 )"
"Şâhin شاهين ( Ebced Değeri: 366 )"
"Şâziye شازيه ( Ebced Değeri: 323 )"
"Şebnem شبنم ( Ebced Değeri: 392 )"
"Şeref شرف  ( Ebced Değeri: 580 )"
"Şerif شريف ( Ebced Değeri: 590 )"
"Şenol شنول ( Ebced Değeri: 386 )"
"Şerife شريفه ( Ebced Değeri: 595 )"
"Şermin شرمين ( Ebced Değeri: 600 )"
"Şöhret شهرت ( Ebced Değeri: 905 )"
"Şükrân شكران ( Ebced Değeri: 571 )"
"Şükriye شكريه ( Ebced Değeri: 535 )"
"Şükrü شكرى ( Ebced Değeri: 530 )"

"Tahsin تحسين ( Ebced Değeri: 528 )"
"Tahir طاهر ( Ebced Değeri: 215 )"
"Talha طلحه ( Ebced Değeri: 52 )"
"Talia طالعه ( Ebced Değeri: 115 )"
"Taner تاڭر ( Ebced Değeri: 621 )"
"Tarık طارق ( Ebced Değeri: 310 )"
"Tayyip طيّب ( Ebced Değeri: 31 )"
"Tenzile تنزيله ( Ebced Değeri: 502 )"
"Teslime تسليمه ( Ebced Değeri: 545 )"
"Tuğba طوبى ( Ebced Değeri: 27 )"
"Tufan طوفان ( Ebced Değeri: 146 )"
"Tülay تولاى ( Ebced Değeri: 447 )"
"Türkan توركان ( Ebced Değeri: 477 )"

"Ufuk افق ( Ebced Değeri: 181 )"
"Uğur اوغور ( Ebced Değeri: 1213 )"
"Umut اوموت ( Ebced Değeri: 453 )"

"Ümran عمران ( Ebced Değeri: 361 )"
"Ümmügülsüm  أمّ كلثوم ( Ebced Değeri: 677 )"
"Ünal اونال ( Ebced Değeri: 88 )"
"Üsame أسامة ( Ebced Değeri: 107 )"


"Vahide واحده ( Ebced Değeri: 24 )"
"Vahit واحد ( Ebced Değeri: 19 )"
"Vasfiye وصفيه ( Ebced Değeri: 191 )"
"Veli ولى ( Ebced Değeri: 46 )"
"Vildan ولدان ( Ebced Değeri: 91 )"

"Yadigar يادكار ( Ebced Değeri: 236 )"
"Yakup يعقوب ( Ebced Değeri: 198 )"
"Yasemin ياسمين ( Ebced Değeri: 171 )"
"Yasin ياسن ( Ebced Değeri: 121 )"
"Yaşar ياشار ( Ebced Değeri: 512 )"
"Yavuz ياووز ( Ebced Değeri: 30 )"
"Yelda يلدا ( Ebced Değeri: 45 )"
"Yeliz يليز ( Ebced Değeri: 57 )"
"Yeşim يشيم ( Ebced Değeri: 360 )"
"Yıldıray يلديراى ( Ebced Değeri: 265 )"
"Yıldırım يلديريم ( Ebced Değeri: 304 )"
"Yıldız ييلديز ( Ebced Değeri: 71 )"
"Yunus ينوس ( Ebced Değeri: 126 )"
"Yusuf يوسف ( Ebced Değeri:156 )"
"Yüksel يوكسل ( Ebced Değeri: 126 )"

"Zafer ظفر ( Ebced Değeri: 1180 )"
"Zarif ظريف ( Ebced Değeri: 1190 )"
"Zeki  زكيّ ( Ebced Değeri: 730 )"
"Zarife ظريفة ( Ebced Değeri: 1195 )"
"Zahide زاهده ( Ebced Değeri: 22 )"
"Zehra زهرا ( Ebced Değeri: 213 )"
"Zekiye ذكيه ( Ebced Değeri: 735 )"
"Zekeriya زكريّا ( Ebced Değeri: 238 )"
"Zeliha زليحا ( Ebced Değeri: 56 )"
"Zennûriye ذنّوريه ( Ebced Değeri: 1021 )"
"Zeynep زينب ( Ebced Değeri: 69 )"
"Ziya ضياء ( Ebced Değeri: 811 )"
"Ziyad زياد ( Ebced Değeri: 22 )"
"Zeytin زيتين ( Ebced Değeri: 477 )"
"Zübeyde زبيده ( Ebced Değeri: 28 )"
"Zühal زحل ( Ebced Değeri: 45 )"
"Zülal زلال ( Ebced Değeri: 68 )"
"Züleyha زليخى ( Ebced Değeri: 657 )"
"Zülfiye زلفيه ( Ebced Değeri: 132 )"
"Zülfü زلفو ( Ebced Değeri: 123 )"




`;

// Her satırı işlemek için metni satır satır böleriz
const lines = originalText.split("\n");

// Her satır için tırnak ekleriz//
const quotedLines = lines.map((line) => `${line},`);

// Yeni metni birleştiririz
const quotedText = quotedLines.join("\n");

// Yeni metni bir dosyaya kaydetmek için fs modülünü kullanabiliriz
fs.writeFileSync("quoted_names2.txt", quotedText, "utf-8", (err) => {
  if (err) {
    console.error("Dosyayı kaydederken bir hata oluştu:", err);
  } else {
    console.log("Dosya başarıyla kaydedildi: quoted_names.txt");
  }
});
